USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'RexUnitTesting')
DROP DATABASE [RexUnitTesting]
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'RexUnitTesting')
BEGIN
CREATE DATABASE [RexUnitTesting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RexUnitTesting', FILENAME = N'c:\temp\RexUnitTesting.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RexUnitTesting_log', FILENAME = N'c:\temp\RexUnitTesting_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO

ALTER DATABASE [RexUnitTesting] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RexUnitTesting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RexUnitTesting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RexUnitTesting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RexUnitTesting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RexUnitTesting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RexUnitTesting] SET ARITHABORT OFF 
GO

ALTER DATABASE [RexUnitTesting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RexUnitTesting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RexUnitTesting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RexUnitTesting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RexUnitTesting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RexUnitTesting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RexUnitTesting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RexUnitTesting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RexUnitTesting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RexUnitTesting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RexUnitTesting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RexUnitTesting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RexUnitTesting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RexUnitTesting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RexUnitTesting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RexUnitTesting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RexUnitTesting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RexUnitTesting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RexUnitTesting] SET  MULTI_USER 
GO

ALTER DATABASE [RexUnitTesting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RexUnitTesting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RexUnitTesting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RexUnitTesting] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RexUnitTesting] SET  READ_WRITE 
GO
